* Config/Preamble :noexport:ATTACH:

:PROPERTIES:
:ID:       8f68008d-a285-4bae-a653-5488ec7ebd44
:END:
 adapted from @aidanscannell/[[https://github.com/aidanscannell/my-org-resume.git][my-org-resume]]
** LaTeX Config :ATTACH:
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \\cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \DeclareNameAlias{sortna nme}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
# #+LATEX_HEADER: \addbibresource{aidan.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
#+AUTHOR: Madhusudan Kumar
#+EXPORT_FILE_NAME: ./resume.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cveventrole \cveventrole{$1}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider\par
#+MACRO: new-page \newpage
#+MACRO: cveventacad \cveventacad{$1}{$2}{$3}{$4}{$5}
#+MACRO: cveventcomp \cveventcomp{$1}{$2}{$3}{$4}{$5}
#+MACRO: cvdomain \cvdomain{$1}
#+MACRO: par \par
#+MACRO: cvproject \cvproject{$1}
#+MACRO: cvsubsection \cvsubsection{$1}

* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Madhusudan Kumar}
\photoR{2.8cm}{logo.png}
\tagline{Machine Learning Engineer}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  %\homepage{None}
  \email{max12525k@gmail.com}
  \phone{+91 9969072292}
  %\location{Mumbai, India}
  \github{max12525k}
  \linkedin{max12525k}
  %\dob{12 Jan 1995}
  %\driving{None}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
%\begin{paracol}{2}
#+end_export
** Personal Statement :ignore:
#+begin_export latex
 \begin{quote}
 Machine Learning Engineer with 5.6 years of experience in applying machine learning, natural language understanding, Generative AI and software engineering to solving problems in smart customer interaction,   threat mapping, predictive maintenance and revenue forecasting. Major career highlights include:

\begin{itemize}
  \item Designed data generation service for rapid dataset delivery & model finetuning for given use case.
  \item Advanced research on multimodal conversational agent by extending previous research.
  \item Led cross functional team to deliver AI-powered application with 50+ backend APIs.
  \item Developed Python Package to reduce model integration time by 60\%.
\end{itemize}
\end{quote}
#+end_export
** Personal Statement Amazon :ignore:noexport:
#+begin_export latex
 \begin{quote}
 ``I am an aspiring data scientist who loves exploring new things with data''
 \end{quote}
#+end_export
** Skills

{{{cvtag(Python)}}}
{{{cvtag(PyTorch)}}}
{{{cvtag(LangChain)}}}
{{{cvtag(GenAI)}}}
{{{cvtag(RAG)}}}
{{{cvtag(Transformers)}}}
{{{cvtag(HuggingFace)}}}
{{{cvtag(Pandas)}}}
{{{cvtag(Scikit-learn)}}}
{{{par-div}}}
{{{cvtag(FastAPI)}}}
{{{cvtag(VectorDB)}}}
{{{cvtag(MongoDB)}}}
{{{cvtag(MYSQL/PostgreSQL)}}}
{{{cvtag(Git)}}}
{{{cvtag(CI/CD)}}}
{{{cvtag(AWS)}}}
{{{cvtag(Linux)}}}
{{{cvtag(Docker)}}}

{{{par}}}

** Professional Experience

*** SDE | Prompt Engineer :ignore:
{{{cvevent(Machine Learning Engineer, Meta | Unifytech, Nov 2023 - Ongoing, Mumbai, India)}}}

{{{cvproject(Project Management)}}}
- Managed 5+ member team of ML engineers and annotators, achieving 10% acceleration in project milestone delivery.
{{{cvproject(AI for Smart Glasses)}}}
- Spearheaded the design and development of scalable data generation service using LangChain, tailored to support diverse finetuning use case, leading to significant reduction in dataset (100K+ samples) delivery time.
- Designed and implemented robust evaluation framework, leveraging quantitative and qualitative metrics to assess large-scale data generation, resulting in enhanced dataset quality by 40% while reducing annotation time by 60%.
- Fine-tuned LLaMA 3 (8B) model on custom dataset, achieving 86% performance improvement in answering user queries in structured format and deployed containerized model for seamless company-wide access on Meta Infra.
# - Successfully containerized and deployed fine-tuned model using Docker, leveraging Kubernetes for orchestration and seamless company-wide accessibility on Meta infrastructure.
{{{cvproject(Research on Conversational Agents)}}}
- Validated findings from research papers by conducting ablation study and identifying key gaps for investigation.
- Extended text-based agent architecture (COOPER) research to build multimodal conversational agents, showcasing performance gains in specialized domains from existing agents.

{{{cvproject(HRMS Chatbot)}}}
- Developed a modular, distributed document processing pipeline with FastAPI, MongoDB and FAISS, streamlining embedding generation and storage for efficient scalability.
- Boosted HR Policy QA performance through strategic RAG implementation and optimized COT prompts.


{{{cvtag(LLAMA3)}}}
{{{cvtag(LangChain)}}}
{{{cvtag(Transformers)}}}
{{{cvtag(PEFT)}}}
{{{cvtag(Cosine Similarity)}}}
{{{cvtag(LLM Evaluation)}}}
{{{cvtag(Docker)}}}
{{{cvtag(FastAPI)}}}
{{{par}}}

*** Senior Data Scientist securethings :ignore:
{{{par-div}}}
{{{cvevent(Senior Data Scientist, SecureThings.AI, Sep 2022 - Sep 2023, Mumbai\, India)}}}

# {{{cvdomain(Automative Cybersecurity)}}}
{{{cvproject(Knowledge Graph Generation with AI)}}}

- Built knowledge graph generation pipeline leveraging SpaCy, extracting 50+ cybersecurity labels and 20+ relationships from 2M+ semi-structured texts with 70%+ accuracy, reduced extraction time by using OpenAI and LangChain.
# - Designed and developed LLM pipeline using LangChain to improve labels and relationship extraction by 15% and reducing the time taken by 90%.
{{{cvproject(Product Development and deployment)}}}
- Built and deployed distributed backend application using FastAPI, AWS Cognito, Docker and MongoDB, supporting a multi-screen product (15+) with extensive API integration (50+), ensuring seamless user experience.
- Deployed AWS pipeline using IaC, reducing management time by 70%, costs by 50%, and deployment time by 80%.
{{{cvtag(NLP)}}}
{{{cvtag(NER)}}}
{{{cvtag(PyTorch)}}}
{{{cvtag(SpaCy)}}}
{{{cvtag(LangChain)}}}
{{{cvtag(FastAPI)}}}
{{{cvtag(MongoDB)}}}
{{{cvtag(Docker)}}}
{{{cvtag(IaC)}}}
{{{cvtag(LLM)}}}
{{{cvtag(OpenAI)}}}

*** Senior Data Scientist TCS :ignore:
{{{par-div}}}
{{{cvevent(Senior Data Scientist, Tata Consultancy Services, Apr 2019 - Sep 2022, Mumbai\, India)}}}

*** Project1 :ignore:
# {{{cvdomain(Telecommunication)}}}
# - Participated in client calls for requirements gathering to refine product roadmap.
# - Collaborated with cross functional team, enabling solution delivery and model expainability.
{{{cvproject(AI Platform for Telecommunication)}}}
- Led the team of 5 developers for web-based ML exploration tool for 40% faster deployment of ML solution.
- Designed 10+ ML solutions for telecom fault and performance management leading to decrease in 15% reduction in events and enable close loop automation for 25% events accross 5000+ sites.
# - Collaborated with clients to reduce the delivery time of mutually agreed milestone by 5%.
# - Collaberated with data engineer, domain expert and solution architect to design federated ML architecture to deploy ML solution across 5000+ sites to limit the response time in seconds

# {{{cvtag(Federated ML)}}}
# {{{cvtag(Scikit-Learn)}}}
# {{{cvtag(Pandas)}}}
# {{{cvtag(Leadership)}}}
# {{{cvtag(Linux)}}}
# {{{cvtag(MLOps)}}}
*** Data Scientist :ignore:
# {{{par-div}}}
{{{cveventrole(Data Scientist)}}}

*** Project1 :ignore:
# {{{cvdomain(Telecommunication)}}}
{{{cvproject(AI Platform for Telecommunication)}}}
- Proposed, designed & built Python package for exploration & integration of 24+ ML use cases across 4+ applications, reducing model training and integration time by 60%.
# - Optimise network management by building usecases for predictive maintenance of network, reduced fault ticket generation and detection of network performance loss (IP filing in progress)
# - Proposed, designed & built Python package for integration of 24+ ML use cases across 4+ applications, reducing integration time by 60%
# - Developed GUI application for end to end exploration of ML use cases by data scientist and domain expert alike
- Enabled one day ahead predictive maintenance, reduced ticket generation by 6% and optimized network performance using forecasting, clustering  and anomaly detection techniques, reducing the operation cost by 18% (POC).
# {{{cvproject(ML Research for Telecommunication)}}}
# - Awarded patent:”METHOD AND SYSTEM FOR ANOMALY DETECTION OF NETWORK KPI” Intellectual Property India Patent No.:202221056578
{{{cvproject(ML for Revenue Forecasting in Insurance)}}}
- Automated and optimized monthly forecasting of claims paid and premium collected, reducing average MAPE by 10%

# - Reduced number of tickets by 6% via automating the identification of alarm’s cluster with root alarm (POC).
# - Improved network performance by deploying anomaly detection algorithm on MS Azure cloud for network loss and latency, detecting half an hour prior to performance degration (Patent in process).
# - Improved decision making by automating and optimising monthly forecasting of claims paid and premium collected by reducing MAPE by 10%.
# - Mentored two peers for integration of ML use cases across 4+ applications

{{{cvtag(Xgboost)}}}
{{{cvtag(Scikit-learn)}}}
{{{cvtag(SARIMAX)}}}
{{{cvtag(Mlextend)}}}
{{{cvtag(Anomaly Detection)}}}
{{{cvtag(Plotly)}}}
{{{cvtag(Pyod)}}}
{{{cvtag(Pytest)}}}
{{{cvtag(AZURE VM)}}}
{{{par}}}
***  Project 2 :ignore:
# {{{par-div}}}
# {{{cvdomain(Insurance)}}}
# {{{cvproject(ML for Revenue Forecasting in Insurance)}}}
# - Automated and optimised monthly forecasting of claims paid and premium collected, reducing average Mape by 10%
# - Explored and generated Covid-19 business impact report against all policies
# - Forecast monthly data storage capacity requirement for effective functioning of database
# - Estimate CRUD execution time for improved delivery of executive reports

# {{{cvtag(Timeseries Forecasting)}}}
# {{{cvtag(Data Analysis)}}}
# {{{cvtag(Reporting)}}}
# {{{cvtag(ARIMA)}}}
# {{{cvtag(Data Analysis)}}}
# {{{cvtag(Data wrangling)}}}
# {{{cvtag(ARIMA)}}}
** Patent
{{{cvsubsection(Patent)}}}
- Awarded patent: "METHOD AND SYSTEM FOR ANOMALY DETECTION OF NETWORK KPI" Intellectual Property India Patent No.:202221056578

** Projects :ignore:noexport:
*** Masters thesis :ignore:
# {{{cveventacad(Reliability Analysis of Self-Aware Components on Network, Indian Institue of Technology\, Bomaby , Prof. M.S. Kulkarni \& Prof. T.K Bhandarkar, July 2017 - Nov 2018, Mumbai\, India)}}}
{{{cveventacad(Masters Thesis, Indian Institue of Technology\, Bomaby , Prof. M.S. Kulkarni, July 2017 - Nov 2018, Mumbai\, India)}}}
- Proposed and Implemented OWL-ontology template to digitally store properties of machine component from different vendors, optimizing the digital processing of components.
- Designed and built process to predict the failure time of new machine on the network to minimize the operation down time using modelled estimation of reliability of mechanical components from loading condition and similarity of components.
# {{{par-div}}}
** Position of Responsibility :noexport:
{{{cvevent(Overall Coordinator, IIT-BBC, Apr 2015 - Mar 2016, Mumbai\, India)}}}
- Sucessfully headed official video channel, leading a team of 6 conveners, creating 60+ videos and covering 35+ events, with nearly 2 million views
# -  Interviewed 10+ Artists & Covered 40+ events in SpicMacay convention 2015
# {{{cvtag(Leadership)}}}
# {{{cvtag(Communication)}}}
# {{{cvtag(Video editing)}}}
# {{{cvtag()}}}


** Newpage :ignore:noexport:
# {{{new-page}}}

** A day of my life :noexport:
# #+begin_export latex
# % \medskip

# % \cvsection{A Day of My Life}

# % % Adapted from @Jake's answer from http://tex.stackexchange.com/a/82729/226
# % % \wheelchart{outer radius}{inner radius}{
# % % comma-separated list of value/text width/color/detail}
# % \wheelchart{1.5cm}{0.5cm}{%
# %   6/8em/accent!30/{Sleep,\\beautiful sleep},
# %   3/8em/accent!40/Eat,
# %   8/8em/accent!60/Work Fast to Sleep More,
# %   2/10em/accent/Sleep More,
# %   5/6em/accent!20/pull everyone's leg,
# % }

# % % use ONLY \newpage if you want to force a page break for
# % % ONLY the current column
# % \newpage
# #+end_export

** Newpage :ignore:noexport:
# {{{new-page}}}


* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
%\switchcolumn
#+end_export

** Skills :ignore:noexport:
{{{cvtag(Python)}}}
{{{cvtag(RAG)}}}
{{{cvtag(Scikit-learn)}}}
{{{cvtag(VectorDB)}}}
{{{cvtag(GenAI)}}}
{{{cvtag(Keras)}}}
{{{cvtag(PyTorch)}}}
{{{cvtag(LangChain)}}}
{{{par-div}}}

{{{cvtag(FastAPI)}}}
{{{cvtag(MongoDB)}}}
{{{cvtag(SQL)}}}
{{{cvtag(MLOPS)}}}
{{{par-div}}}

{{{cvtag(Git)}}}
{{{cvtag(IaC)}}}
{{{cvtag(AWS)}}}
{{{cvtag(Linux)}}}
{{{cvtag(Docker)}}}


** Education

*** Research Intership :ignore:
# {{{par-div}}}
# {{{cvevent(Research Internship, Chiba University, May 2016 - Jun 2016, Chiba\, Japan)}}}
 {{{cveventacad(Internship, Chiba University, Prof. T. Sakurai, May 2016 - Jun 2016, Chiba\, Japan)}}}

- Explored linear diffusive coupled neurons (FHN coupled system) with external forcing to study pattern formation
- Conducted nonlinear stability analysis to obtain significant parameters & visualize their behavior near stability points to understand contribution to pattern formation

{{{cvtag(Visualization)}}}
{{{cvtag(MATLAB)}}}
{{{cvtag(Linear algebra)}}}
{{{cvtag(Overseas Experience)}}}
{{{par-div}}}

{{{cvevent(M.Tech\ in Mechanical Engineering, IIT-B, Jul 2017 - Nov 2018,)}}}
# - Specialization in CADA
- Proposed and implemented OWL-ontology based template to digitally store properties of machine component from different vendors, optimizing the digital processing of components infromation.
- Designed and built process to predict the failure time of new machine on the network based on other machine failure data by modelled estimation of reliability of mechanical components from loading condition and similarity of components, minimizing the operation downtime.

# {{{divider}}}

{{{cvevent(B.Tech\ in Mechanical Engineering, IIT-B, Jul 2013 - Jun 2017,)}}}
- Attended courses related to statistics, data analysis, computer programing and mechanical engineering.
- Conducted research in non-linear dynamics, brain entrainment using mathematical modeling and simulations.
- Headed official video channel of IIT-BBC, leading a team of 6 conveners, creating 60+ videos and covering 35+ events, with nearly 2 million views.
# {{{divider}}}
# {{{cvevent(Internship\ in Non Linear Dynamics, Chiba University, May 2016 - Jun 2016,)}}}
# - Researched on pattern formation and created meaningful visualization.




** Education condensed :ignore:noexport:
** Education :ignore:noexport:
{{{cvevent(M.Tech+B.Tech\ in Mechanical Engineering, Indian Institute of Technology Bombay, Jul 2013 - Nov 2018, Mumbai\, India)}}}

- Sucessfully designed process to predict failure time of machines on the network to minimize the operation downtime.
- Proposed and implemented standard template using owl ontology to digitally store properties of machine component from different vendors.
- Sucessfully headed official video channel, leading a team of 6 conveners, creating 60+ videos and covering 35+ events, with nearly 2 million views.
- Researched on pattern formation and created meaningful visualization as an Intern in non-linear dynamics at Chiba University, Japan.
** Newpage :ignore:noexport:
#+BEGIN_EXPORT latex
% \newpage
#+END_EXPORT

** My Life Philosophy :noexport:
#+begin_export latex
% \begin{quote}
% ``Love''
% \end{quote}
#+end_export

# ** Most Proud Of :ignore:
# #+begin_export latex
# \cvsection{Most Proud of}
# #+end_export

# #+begin_export latex
#
# #+end_export

# #+begin_export latex
# \divider

# #+end_export

** Extracurricular :ignore:noexport:

# - Sucessfully headed official video channel of IIT-BBC, leading a team of 6 conveners, creating 60+ videos and covering 35+ events, with nearly 2 million views.
# - Mentored 100+ students to produce 20+ short films during Freshizza festival
- Core team member of "Mechanical Freshie", a video with more than 630,000 views.
- Supported students with physics classes for IIT-JEE exam.
# {{{cvachievement(\faCertificate,Mentor freshmen in Video E, )}}}
# - Customize emacs in free time for optimised development
# {{{divider}}}

** Certification :ignore:noexport:

- Data Analysis with Pandas and Python
- Python for Timeseries Data Analysis
# {{{cvachievement(\faTrophy,abc , Bronze/Silver/Gold)}}}

** Languages :noexport:
#+begin_export latex
% \cvsection{Languages}

% \cvskill{English}{5}
% \divider

% \cvskill{Hindi}{4}
% \divider

% \cvskill{Bhojpuri}{3}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \medskip
#+end_export


* Back Matter :ignore:
#+begin_export latex
%\end{paracol}
%\end{document}
#+end_export
